# fly.toml app configuration file generated for gerador-frequncia-vcs on 2025-08-14T07:41:43-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gerador-frequncia-vcs'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = "connections"
    soft_limit = 20
    hard_limit = 25

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
